[parameters]
# Enables the scheduler that processes xmppmaster.reset_machine queue
regenerate_queue_scan_enabled = True

# Interval in seconds between each queue scan.
# A lower bound of 10s is enforced by the plugin.
regenerate_queue_scan_interval = 20

# Maximum number of machines sent to one same relay in a batch.
# The relay will then process them sequentially.
regenerate_queue_batch_size = 5
