[parameters]
# Enable or disable periodic processing of reset_machine queue.
reset_queue_scan_enabled = True

# Interval in seconds between each queue scan.
# A lower bound of 10s is enforced by the plugin.
reset_queue_scan_interval = 60
