#!/bin/bash

# -*- coding: utf-8; -*-
#
# (c) 2018 siveo, http://www.siveo.net
#
# Author(s):
#
# This file is part of Pulse 2, http://www.siveo.net
#
# Pulse 2 is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# Pulse 2 is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Pulse 2.  If not, see <http://www.gnu.org/licenses/>.

echo "INFO: Generating package ${PACKAGE_NAME}..."

# Detect if uuid or uuidgen is available
if [ -x "$(command -v uuid)" ]; then
    PACKAGE_UUID=$(uuid)
    echo "  Package UUID: ${PACKAGE_UUID}"
elif [ -x "$(command -v uuidgen)" ]; then
    PACKAGE_UUID=$(uuidgen)
    echo "  Package UUID: ${PACKAGE_UUID}"
else
  echo "ERROR: Please install uuid or uuidgen."
  exit 1
fi

# A few settings
PACKAGE_NAME="Medulla Kiosk"
PACKAGE_DESC="Kiosk module for machines managed by Medulla"

KIOSK_VERSION="1.0.0"
PYTHON_VERSION="3.11.7"
WIN64_PYTHON_FILENAME="python-${PYTHON_VERSION}-amd64.exe"
WIN64_PYWIN32_FILENAME="pywin32-306-cp311-cp311-win_amd64.whl"
WIN64_PYQT6_SIP_DEPS_1_FILENAME="sip-6.8.2-py3-none-any.whl"
WIN64_PYQT6_FILENAME="PyQt6-6.6.1-cp38-abi3-win_amd64.whl"
WIN64_PYQT6_QT6_FILENAME="PyQt6_Qt6-6.6.1-py3-none-win_amd64.whl"
WIN64_PYQT6_SIP_FILENAME="PyQt6_sip-13.6.0-cp311-cp311-win_amd64.whl"
WIN64_WHEEL_FILENAME="wheel-0.42.0-py3-none-any.whl"
PULSE_KIOSK_FILENAME="kiosk-interface-${KIOSK_VERSION}.tar.gz"
PULSE_KIOSK_PATH="/var/lib/pulse2/clients"
PULSE_KIOSK_DEPS_PATH="/var/lib/pulse2/clients/win/downloads"


#### CREATE KIOSK PACKAGE
# First check if the package exists.
# If it is the case, keep its uuid for deleting it after generation.
old_uuid=$(grep "${PACKAGE_NAME} v${AGENT_VERSION}" /var/lib/pulse2/packages/sharing/global/* -R | grep xmppdeploy.json | grep -P -o '[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}')

# Create the package
mkdir -p /var/lib/pulse2/packages/sharing/global/${PACKAGE_UUID}
pushd /var/lib/pulse2/packages/sharing/global/${PACKAGE_UUID}

# Python
cp ${PULSE_KIOSK_DEPS_PATH}/${WIN64_PYTHON_FILENAME} .
PYTHON_INSTALL_COMMAND="${WIN64_PYTHON_FILENAME} /quiet InstallAllUsers=1 Include_pip=0 TargetDir=\"c:\\Program Files\\Python3\"\n
C:\\Progra~1\\Python3\\python.exe -m ensurepip --upgrade\n"
PYTHON_INSTALL_COMMAND_ENCODED=$(echo -e ${PYTHON_INSTALL_COMMAND} | base64 --wrap=0)

# Python modules
cp ${PULSE_KIOSK_DEPS_PATH}/python_modules/${WIN64_PYWIN32_FILENAME} .
cp ${PULSE_KIOSK_DEPS_PATH}/python_modules/${WIN64_PYQT6_FILENAME} .
cp ${PULSE_KIOSK_DEPS_PATH}/python_modules/${WIN64_PYQT6_QT6_FILENAME} .
cp ${PULSE_KIOSK_DEPS_PATH}/python_modules/${WIN64_PYQT6_SIP_FILENAME} .
cp ${PULSE_KIOSK_DEPS_PATH}/python_modules/${WIN64_PYQT6_SIP_DEPS_1_FILENAME} .
cp ${PULSE_KIOSK_DEPS_PATH}/python_modules/${WIN64_WHEEL_FILENAME} .
PYWIN32_INSTALL_COMMAND="py -3 -m pip install --upgrade --no-index --find-links=\".\" ${WIN64_PYWIN32_FILENAME}"
PYWIN32_INSTALL_COMMAND_ENCODED=$(echo -e ${PYWIN32_INSTALL_COMMAND} | base64 --wrap=0)
PYQT6_INSTALL_COMMAND="py -3 -m pip install --upgrade --no-index --find-links=\".\" ${WIN64_PYQT6_FILENAME}"
PYQT6_INSTALL_COMMAND_ENCODED=$(echo -e ${PYQT6_INSTALL_COMMAND} | base64 --wrap=0)
WHEEL_INSTALL_COMMAND="py -3 -m pip install --upgrade --no-index --find-links=\".\" ${WIN64_WHEEL_FILENAME}"
WHEEL_INSTALL_COMMAND_ENCODED=$(echo -e ${WHEEL_INSTALL_COMMAND} | base64 --wrap=0)

# Kiosk
cp ${PULSE_KIOSK_PATH}/${PULSE_KIOSK_FILENAME} .
KIOSK_INSTALL_COMMAND="py -3 -m pip install --upgrade --no-index --find-links=\".\" ${PULSE_KIOSK_FILENAME}"
KIOSK_INSTALL_COMMAND_ENCODED=$(echo -e ${KIOSK_INSTALL_COMMAND} | base64 --wrap=0)

# Generate xmppdeploy.json
cat <<EOF > xmppdeploy.json
{
    "info": {
        "localisation_server": "global",
        "previous_localisation_server": "global",
        "description": "${PACKAGE_DESC}",
        "name": "${PACKAGE_NAME} v${KIOSK_VERSION}",
        "software": "${PACKAGE_NAME}",
        "transferfile": true,
        "methodetransfert": "pushrsync",
        "Dependency": [],
        "version": "${KIOSK_VERSION}",
        "metagenerator": "manual"
    },
    "win": {
        "sequence": [
            {
                "step": 0,
                "error": 1,
                "success": 2,
                "actionlabel": "3837583a",
                "action": "actionprocessscript",
                "command": "py -3 -V",
                "codereturn": "",
                "@resultcommand": "@resultcommand"
            },
            {
                "step": 1,
                "error": 7,
                "success": 2,
                "actionlabel": "5b10d6ae4d7b9",
                "action": "actionprocessscriptfile",
                "typescript": "Batch",
                "script": "${PYTHON_INSTALL_COMMAND_ENCODED}",
                "codereturn": "",
                "@resultcommand": "@resultcommand"
            },
            {
                "step": 2,
                "error": 7,
                "success": 3,
                "actionlabel": "f81c3cc2",
                "action": "actionprocessscriptfile",
                "typescript": "Batch",
                "script": "${PYWIN32_INSTALL_COMMAND_ENCODED}",
                "codereturn": "",
                "@resultcommand": "@resultcommand"
            },
            {
                "step": 3,
                "error": 7,
                "success": 4,
                "actionlabel": "f8bd0cd6",
                "action": "actionprocessscriptfile",
                "typescript": "Batch",
                "script": "${PYQT6_INSTALL_COMMAND_ENCODED}",
                "codereturn": "",
                "@resultcommand": "@resultcommand"
            },
            {
                "step": 4,
                "error": 7,
                "success": 5,
                "actionlabel": "a5f343dd",
                "action": "actionprocessscriptfile",
                "typescript": "Batch",
                "script": "${WHEEL_INSTALL_COMMAND_ENCODED}",
                "codereturn": "",
                "@resultcommand": "@resultcommand"
            },
            {
                "step": 5,
                "error": 7,
                "success": 6,
                "actionlabel": "e11c5ac2",
                "action": "actionprocessscriptfile",
                "typescript": "Batch",
                "script": "py -3 -m pip install --upgrade --no-index --find-links=\".\" ${PULSE_KIOSK_FILENAME}",
                "codereturn": "",
                "@resultcommand": "@resultcommand"
            },
            {
                "step": 6,
                "action": "actionsuccescompletedend",
                "actionlabel": "END_SUCCESS"
            },
            {
                "step": 7,
                "action": "actionerrorcompletedend",
                "actionlabel": "END_ERROR"
            }
        ]
    },
    "metaparameter": {
        "win": {
            "label": {
                "3837583a": 0,
                "5b10d6ae4d7b9": 1,
                "f81c3cc2": 2,
                "f8bd0cd6": 3,
                "a5f343dd": 4,
                "e11c5ac2": 5,
                "END_SUCCESS": 6,
                "END_ERROR": 7
            }
        },
        "os": [
            "win"
        ]
    }
}
EOF

# Generate conf.json
cat <<EOF > conf.json
{"commands":{"postCommandSuccess":{"command": "", "name": ""},"installInit": {"command": "", "name": ""},"postCommandFailure": {"command": "", "name": ""},"command": {"command": "DO NOT EDIT THIS PACKAGE", "name": ""},"preCommand": {"command": "", "name": ""}}, "description": "${PACKAGE_DESC}","targetos": "win", "entity_id": "0", "sub_packages": [], "localisation_server": "global", "previous_localisation_server": "global", "reboot": 0, "version": "${KIOSK_VERSION}",
"inventory": {"associateinventory": "0", "licenses": "", "queries": {"Qversion": "", "Qvendor": "", "boolcnd": "", "Qsoftware": ""}}, "id": "${PACKAGE_UUID}", "name": "${PACKAGE_NAME} v${KIOSK_VERSION}", "metagenerator": "manual"}
EOF

popd

echo "INFO: Generating package ${PACKAGE_NAME}... Done"

# Change permissions on the package
chown -R syncthing: /var/lib/pulse2/packages/sharing/global/${PACKAGE_UUID}

# Delete old version if found
if [[ ${old_uuid} != '' ]]; then
  echo "INFO: Deleting pakage ${old_uuid}..."
  rm -rf /var/lib/pulse2/packages/sharing/global/${old_uuid}
  echo "INFO: Deleting pakage ${old_uuid}... Done"
fi

# Insert package in database
echo "INFO: Generating package links and database records..."
DBHOST=$(crudini --get /etc/mmc/plugins/pkgs.ini.local database dbhost 2> /dev/null || echo localhost)
DBPORT=$(crudini --get /etc/mmc/plugins/pkgs.ini.local database dbport 2> /dev/null || echo 3306)
DBPASS=$(crudini --get /etc/mmc/plugins/pkgs.ini.local database dbpasswd)
DBUSER=$(crudini --get /etc/mmc/plugins/pkgs.ini.local database dbuser 2> /dev/null || echo mmc)
/usr/sbin/pulse2-generation_package.py -H ${DBHOST} -P ${DBPORT} -u ${DBUSER} -p ${DBPASS} -g -m -l -r > /tmp/pulse2-generation_package.log
echo "INFO: Generating package links and database records... Done"
