[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "pulse_machine_plugins"
version = "5.6.3"
dynamic = ["dependencies"]
requires-python = ">=3.7"
authors = [
  {name = "Medulla", email = "contact@medulla-tech.io"}
]
maintainers = [
  {name = "Medulla", email = "contact@medulla-tech.io"}
]
description = "XMPP Machine agent plugins for Medulla"
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
keywords = ["pulse-xmpp-agent"]
classifiers = [
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.13",
]

[tool.setuptools.dynamic]
dependencies = { file = ["requirements.txt"] }

[project.urls]
Homepage = "https://medulla-tech.io/"
Documentation = "https://docs.medulla-tech.io/"
Repository = "https://github.com/medulla-tech/medulla-agent"
"Bug Tracker" = "https://github.com/medulla-tech/medulla-agent"
Changelog = "https://github.com/medulla-tech/medulla-agent"