#!/bin/sh
# postinst script for #PACKAGE#
#
# see: dh_installdeb(1)

set -e

rm -fv /var/lib/medulla/imaging/postinst/winutils/Medulla-Agent*latest* 

if [ ! -d "/var/lib/medulla/clients/win" ]; then
    mkdir /var/lib/medulla/clients/win
fi

if [ -d "/var/lib/medulla/clients/win32" ]; then
    mv /var/lib/medulla/clients/win32/*.exe /var/lib/medulla/clients/win/
    rm -fr /var/lib/medulla/clients/win32/
fi

if [ -d "/var/lib/medulla/clients/linux" ]; then
    rm -fr /var/lib/medulla/clients/linux/
fi

#DEBHELPER#

exit 0
