#!/bin/sh
set -e

systemctl daemon-reload

if [ -f "/usr/lib/python2.7/dist-packages/pulse_xmpp_agent/BOOL_UPDATE_AGENT" ]; then
    rm -f /usr/lib/python2.7/dist-packages/pulse_xmpp_agent/BOOL_UPDATE_AGENT
fi

case "$1" in
    configure)
        if ! getent passwd | grep -q "^reversessh:"; then
            echo -n "Adding user reversessh..."
            adduser --system \
                    --home /var/lib/pulse2/clients/reversessh \
                    --shell /bin/rbash \
                    --disabled-password \
                    reversessh 2>/dev/null || true
            echo "..done"
        fi
        if [ ! -f "/var/lib/pulse2/clients/reversessh/.ssh/id_rsa" ]; then
            echo -n "Generating ssh key..."
            mkdir -p /var/lib/pulse2/clients/reversessh/.ssh
            ssh-keygen -q -N "" -b 2048 -t rsa -f /var/lib/pulse2/clients/reversessh/.ssh/id_rsa
            cp -a /var/lib/pulse2/clients/reversessh/.ssh/id_rsa.pub /var/lib/pulse2/clients/reversessh/.ssh/authorized_keys
            chown -R reversessh: /var/lib/pulse2/clients/reversessh/.ssh
            chmod 700 /var/lib/pulse2/clients/reversessh/.ssh
            chmod 600 /var/lib/pulse2/clients/reversessh/.ssh/authorized_keys
            echo "..done"
        fi
        if systemctl is-enabled pulse-xmpp-agent-relay &>/dev/null ; then
            systemctl restart pulse-xmpp-agent-relay
        fi
        if systemctl is-enabled pulse-xmpp-agent-log &>/dev/null ; then
            systemctl restart pulse-xmpp-agent-log
        fi
        if systemctl is-enabled pulse-package-watching &>/dev/null ; then
            systemctl restart pulse-package-watching
        fi
        ;;
esac

#DEBHELPER#

exit 0
