#!/bin/sh
set -e

systemctl daemon-reload

if [ -f "/usr/lib/python2.7/dist-packages/pulse_xmpp_agent/BOOL_UPDATE_AGENT" ]; then
    rm -f /usr/lib/python2.7/dist-packages/pulse_xmpp_agent/BOOL_UPDATE_AGENT
fi

case "$1" in
    configure)
        if ! getent passwd | grep -q "^reversessh:"; then
            echo -n "Adding user reversessh..."
            adduser --system \
                    --home /var/lib/pulse2/clients/reversessh \
                    --shell /bin/rbash \
                    --disabled-password \
                    reversessh 2>/dev/null || true
            echo "..done"
        fi
        if [ ! -f "/var/lib/pulse2/clients/reversessh/.ssh/id_rsa" ]; then
            echo -n "Generating ssh key..."
            mkdir -p /var/lib/pulse2/clients/reversessh/.ssh
            ssh-keygen -q -N "" -b 2048 -t rsa -f /var/lib/pulse2/clients/reversessh/.ssh/id_rsa
            cp -a /var/lib/pulse2/clients/reversessh/.ssh/id_rsa.pub /var/lib/pulse2/clients/reversessh/.ssh/authorized_keys
            chown -R reversessh: /var/lib/pulse2/clients/reversessh/.ssh
            chmod 700 /var/lib/pulse2/clients/reversessh/.ssh
            chmod 600 /var/lib/pulse2/clients/reversessh/.ssh/authorized_keys
            echo "..done"
        fi
        SERVICES='pulse-xmpp-agent-relay \
                  pulse-xmpp-agent-log \
                  pulse-package-watching'
        for service in ${SERVICES}; do
            if systemctl is-enabled ${service} &>/dev/null ; then
                echo "Restarting ${service}"
                systemctl restart ${service}
            fi
        done
        ;;
esac

#DEBHELPER#

exit 0
