#!/bin/sh
# postinst script for #PACKAGE#
#
# see: dh_installdeb(1)

set -e

# We try to generate the full and minimal agents
cd /var/lib/pulse2/clients
if [ -f /var/lib/pulse2/clients/config/agentconf.ini ]; then
    ./generate-pulse-agent.sh
    ./generate-pulse-agent.sh --minimal
    ./generate-agent-package
fi

chown -R syncthing: /var/lib/pulse2/xmpp_baseremoteagent/
chown -R syncthing: /var/lib/pulse2/clients/

systemctl daemon-reload

#DEBHELPER#

exit 0
