[parameters]
# used by plugin_resultdiskmastering to know where to find the davos/plugins base plugins
diskmastering_path=/var/lib/pulse2/imaging
diskmastering_path_plugin_base=/var/lib/pulse2/imaging/davos/xmpp_plugins
