#!/bin/bash

# Delay startup until vnc and ssh daemons have started
sleep 60

# Start the agent
export PYCURL_SSL_LIBRARY=openssl
/usr/bin/python3 /usr/local/lib/python3/site-packages/medulla_agent/launcher.py -t machine
